name: portfolios

services:
  portfolios-db:
    image: postgres:13-alpine
    env_file:
      - path: ./.env
        required: false
    volumes:
      - portfolios_db_data:/var/lib/postgresql/data

  portfolios:
    build:
      context: .
      dockerfile: ../../base.Dockerfile
      additional_contexts:
        - shared-context=../../shared
    env_file:
      - path: ./.env
        required: false
    depends_on: [portfolios-db]

volumes:
  portfolios_db_data:
