services:
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    build:
      target: development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/alembic.ini:/app/alembic.ini
      - ./backend/app/alembic/:/app/alembic/

  worker:
    volumes:
      - ./backend/app:/app/app

  scheduler:
    volumes:
      - ./backend/app:/app/app

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    ports: ["8081:80"]

  adminer:
    image: adminer
    ports: ["8082:8080"]
