services:
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  init:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: >
      sh -c "alembic upgrade head && python -m app.scripts.seed"
    env_file:
      - path: ./.env
        required: false
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/alembic.ini:/app/alembic.ini
      - ./backend/app/alembic/:/app/alembic/
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  backend:
    build:
      target: development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/alembic.ini:/app/alembic.ini
      - ./backend/app/alembic/:/app/alembic/
      - ./backend/static:/app/static
    depends_on:
      init:
        condition: service_completed_successfully
      redis:
        condition: service_started

  worker:
    volumes:
      - ./backend/app:/app/app
      - ./backend/static:/app/static

  scheduler:
    volumes:
      - ./backend/app:/app/app
      - ./backend/static:/app/static

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    ports: ["8081:80"]

  adminer:
    image: adminer
    ports: ["8082:8080"]
