services:
  admin-db:
    image: mariadb
    container_name: admin-db
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ADMIN_DB_NAME}
      - MYSQL_USER=${ADMIN_DB_USER}
      - MYSQL_PASSWORD=${ADMIN_DB_PASSWORD}
    volumes:
      - admin_db_data:/var/lib/mysql
      - ./databases/dumps/admin/:/docker-entrypoint-initdb.d/
    networks:
      - portfolios-net
    restart: unless-stopped
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RELOAD=true
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - admin-db
    networks:
      - portfolios-net
    restart: unless-stopped
    volumes:
      - ./backend/app:/app/app
      - ./shared-configs/common.env:/app/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - FAST_REFRESH=true
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    networks:
      - portfolios-net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - portfolios-net

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - admin-db
    networks:
      - portfolios-net

networks:
  portfolios-net:
    driver: bridge


volumes:
  admin_db_data:
