"""initial

Revision ID: 01773f2e3fa1
Revises: 
Create Date: 2026-07-14 06:24:33.943794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01773f2e3fa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_id'), 'portfolio', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_table('provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('requests_per_hour', sa.Integer(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('requests_per_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_delay', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.BigInteger(), nullable=False),
    sa.Column('successful_requests', sa.BigInteger(), nullable=False),
    sa.Column('failed_requests', sa.BigInteger(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_table('ticker',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('symbol', sa.String(length=124), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_market'), 'ticker', ['market'], unique=False)
    op.create_index(op.f('ix_ticker_symbol'), 'ticker', ['symbol'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker_id', sa.String(length=32), nullable=False),
    sa.Column('ticker2_id', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('quantity2', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('price_usd', sa.Numeric(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('wallet2_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('portfolio2_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_active_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=False)
    op.create_table('portfolio_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.String(length=256), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('buy_orders', sa.Numeric(), nullable=False),
    sa.Column('sell_orders', sa.Numeric(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('realized_profit', sa.Numeric(), nullable=False),
    sa.Column('total_invested', sa.Numeric(), nullable=False),
    sa.Column('percent', sa.Numeric(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_asset_id'), 'portfolio_asset', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('taggable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('task_priority', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_result', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.BigInteger(), nullable=False),
    sa.Column('success_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_provider_id'), 'task', ['provider_id'], unique=False)
    op.create_table('wallet_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.String(length=256), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('buy_orders', sa.Numeric(), nullable=False),
    sa.Column('sell_orders', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refresh_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_id')
    )
    op.create_table('request_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('was_successful', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body_preview', sa.Text(), nullable=True),
    sa.Column('response_content_type', sa.String(length=200), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_log_provider_id'), 'request_log', ['provider_id'], unique=False)
    op.create_index(op.f('ix_request_log_task_id'), 'request_log', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_log_task_id'), table_name='request_log')
    op.drop_index(op.f('ix_request_log_provider_id'), table_name='request_log')
    op.drop_table('request_log')
    op.drop_table('login_sessions')
    op.drop_table('wallet_asset')
    op.drop_index(op.f('ix_task_provider_id'), table_name='task')
    op.drop_table('task')
    op.drop_table('taggable')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_portfolio_asset_id'), table_name='portfolio_asset')
    op.drop_table('portfolio_asset')
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_ticker_symbol'), table_name='ticker')
    op.drop_index(op.f('ix_ticker_market'), table_name='ticker')
    op.drop_table('ticker')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('provider')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_id'), table_name='portfolio')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
