name: portfolios

services:
  market-db:
    image: postgres:13-alpine
    env_file:
      - path: ./.env
        required: false
    volumes:
      - market_db_data:/var/lib/postgresql/data

  market:
    build:
      context: .
      dockerfile: ../../base.Dockerfile
      additional_contexts:
        - shared-context=../../shared
    env_file:
      - path: ./.env
        required: false
    depends_on: [market-db]

  market-celery-worker:
    build:
      context: .
      dockerfile: ../../base.Dockerfile
      additional_contexts:
        - shared-context=../../shared

  market-celery-beat:
    build:
      context: .
      dockerfile: ../../base.Dockerfile
      additional_contexts:
        - shared-context=../../shared

volumes:
  market_db_data:
