FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY --from=shared-context . /app/shared
RUN ln -s /app/shared /app/node_modules/@shared

COPY . .
RUN npm run build

FROM nginx:alpine AS serve
COPY --from=build /app/build /usr/share/nginx/html
