name: portfolios

services:
  auth-db:
    image: postgres:18-alpine
    env_file:
      - path: ./.env
        required: false
    volumes:
      - auth_db_data:/var/lib/postgresql

  auth:
    build:
      context: .
      dockerfile: ../../base.Dockerfile
      additional_contexts:
        - shared-context=../../shared
    env_file:
      - path: ../../../.env
        required: false
      - path: ./.env
        required: false
    depends_on: [auth-db]

volumes:
  auth_db_data:
